### ISSUE TITLE
Todo mvp

### ISSUE THREAD

**Issue by bodinsamuel** [bodinsamuel/repo-linter#2]
- [ ] Generate Base content
  - [ ] Execute yarn init
  - [ ] Execute tsc
- [ ] Put all js related to a js/ namespace
- [ ] Test
- [ ] Basename variant (dotfile vs non dotfile)
- [ ] eslintrc: should extends option
- [ ] renovaterc: should extends option
